# Generated by Django 5.2.13 on 2026-04-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PillDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "item_seq",
                    models.CharField(db_column="item_seq", max_length=20, unique=True),
                ),
                (
                    "effect_text",
                    models.TextField(blank=True, db_column="effect_text", null=True),
                ),
                (
                    "usage_text",
                    models.TextField(blank=True, db_column="usage_text", null=True),
                ),
                (
                    "warning_text",
                    models.TextField(blank=True, db_column="warning_text", null=True),
                ),
                (
                    "storage_text",
                    models.TextField(blank=True, db_column="storage_text", null=True),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True, db_column="source_url", max_length=500, null=True
                    ),
                ),
                (
                    "crawl_status",
                    models.CharField(
                        blank=True, db_column="crawl_status", max_length=50, null=True
                    ),
                ),
                (
                    "crawled_at",
                    models.DateTimeField(blank=True, db_column="crawled_at", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "pill_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PillMaster",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "k_code",
                    models.CharField(db_column="k_code", max_length=20, unique=True),
                ),
                (
                    "item_seq",
                    models.CharField(db_column="item_seq", max_length=20, unique=True),
                ),
                (
                    "item_name",
                    models.CharField(
                        blank=True, db_column="dl_name", max_length=255, null=True
                    ),
                ),
                (
                    "entp_name",
                    models.CharField(
                        blank=True, db_column="dl_company", max_length=255, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "pill_master",
                "managed": False,
            },
        ),
    ]
