# Generated by Django 5.2.13 on 2026-04-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pills", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pillmaster",
            options={"managed": False, "ordering": ["-created_at"]},
        ),
    ]
